<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
		<OutputType>Exe</OutputType>
		<AssemblyName>_ConsoleApp</AssemblyName>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Grpc.Net.Client" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" />
		<PackageReference Include="Microsoft.Net.Compilers.Toolset">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\DiagnosticExplorer.Hosting\DiagnosticExplorer.Hosting.csproj" />
		<ProjectReference Include="..\DiagnosticExplorer\DiagnosticExplorer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Processes.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
